name: Deploy to GKE (ADM)

on:
  push:
    branches: ["main"]

jobs:
  deploy-gke:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    # Auth ke Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Auth Docker to Artifact Registry
    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev

    # Build & Push image
    - name: Build and Push image
    - run: |
        PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
        IMAGE
