name: CI - Build And Push Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    # ⛔ FIX UTAMA → login pakai PAT + username lowercase
    - name: Login to GitHub Container Registry (with PAT)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: wilsonn06
        password: ${{ secrets.GHCR_PAT }}

    # Build image
    - name: Build Docker image
      run: |
        OWNER="wilsonn06"
        IMAGE_NAME=ghcr.io/$OWNER/s-rusun-adm:latest
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        docker build -t $IMAGE_NAME .

    # Push image
    - name: Push Docker image
      run: docker push $IMAGE_NAME

    # Notify repo infra
    - name: Notify infra repo to deploy
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.REPO_PAT }}
        repository: wilsonn06/s-rusun-infra
        event-type: image-update
        client-payload: |
          {
            "service": "s-rusun-adm",
            "image": "${{ env.IMAGE_NAME }}"
          }
